/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.dbConnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author milan
 */
public class SendMoneyDashoard extends javax.swing.JFrame {

    /**
     * Creates new form SendMoneyDashoard
     */
    public SendMoneyDashoard() {
        initComponents();
    }

      public void logEvent(int userId, String username, String description) {
    dbConnector dbc = new dbConnector();
    Connection con = dbc.getConnection();
    PreparedStatement pstmt = null;

    try {
        // Fixed: include `log_description` in your INSERT
        String sql = "INSERT INTO tbl_log (u_id, u_username, login_time, u_type, log_status, log_description) VALUES (?, ?, ?, ?, ?, ?)";
        pstmt = con.prepareStatement(sql);

        pstmt.setInt(1, userId);
        pstmt.setString(2, username);
        pstmt.setTimestamp(3, new Timestamp(new Date().getTime())); // login_time
        pstmt.setString(4, "Success - User Action"); // u_type (general category)
        pstmt.setString(5, "Active"); // log_status
        pstmt.setString(6, description); // log_description (e.g., "User Reset Their Password")

        pstmt.executeUpdate();
        System.out.println("Log event recorded successfully.");
    } catch (SQLException e) {
        System.out.println("Error recording log: " + e.getMessage());
    } finally {
        try {
            if (pstmt != null) pstmt.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error closing resources: " + e.getMessage());
        }
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Senderusername = new javax.swing.JTextField();
        loanamount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Receivername = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acc_fname = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Senderusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenderusernameActionPerformed(evt);
            }
        });
        jPanel5.add(Senderusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 40));
        jPanel5.add(loanamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Send Amount");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(27, 57, 77));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel5.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 70, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Sender Username");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        Receivername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceivernameActionPerformed(evt);
            }
        });
        jPanel5.add(Receivername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 40));

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 590, 410));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jLabel4.setText("SEND MONEY DASHBOARD");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 630, 560));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/VVT.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 70));

        acc_fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        acc_fname.setText("USER");
        jPanel1.add(acc_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));

        acc_id.setText("USER ID");
        jPanel1.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SenderusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenderusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenderusernameActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

        UserDashboard ru = new UserDashboard();
        ru.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void ReceivernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceivernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceivernameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Session sess = Session.getInstance();
    int senderId = sess.getUid(); // Get sender's user ID

    if (senderId <= 0) {
        JOptionPane.showMessageDialog(this, "User not logged in!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get input values
    String senderUsername = Senderusername.getText().trim();
    String receiverUsername = Receivername.getText().trim();
    String amountStr = loanamount.getText().trim(); // Assuming your amount textfield is loanamount

    if (senderUsername.isEmpty() || receiverUsername.isEmpty() || amountStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        double amount = Double.parseDouble(amountStr);

        // Amount validation
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "Send amount must be greater than 0.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (amount > 1000000) {
            JOptionPane.showMessageDialog(this, "Send amount exceeds the maximum allowed (₱1,000,000).", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        dbConnector dbc = new dbConnector();
        try (Connection conn = dbc.getConnection()) {
            conn.setAutoCommit(false); // Start transaction

            // 🔵 Check if receiver is a normal user (not an admin)
            String userTypeQuery = "SELECT u_type FROM tbl_users WHERE u_username = ?";
            try (PreparedStatement pstUserType = conn.prepareStatement(userTypeQuery)) {
                pstUserType.setString(1, receiverUsername);
                ResultSet rsUserType = pstUserType.executeQuery();

                if (rsUserType.next()) {
                    String userType = rsUserType.getString("u_type");
                    if ("admin".equalsIgnoreCase(userType)) {
                        JOptionPane.showMessageDialog(this, "Cannot send money to an Admin account!", "Validation Error", JOptionPane.WARNING_MESSAGE);
                        conn.rollback();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Receiver not found!", "Error", JOptionPane.ERROR_MESSAGE);
                    conn.rollback();
                    return;
                }
            }

            // 🔵 Get sender's current balance
            String balanceQuery = "SELECT balance FROM tbl_users WHERE u_username = ?";
            try (PreparedStatement pstBalance = conn.prepareStatement(balanceQuery)) {
                pstBalance.setString(1, senderUsername);
                ResultSet rs = pstBalance.executeQuery();

                double senderBalance = 0.0;
                if (rs.next()) {
                    senderBalance = rs.getDouble("balance");
                } else {
                    JOptionPane.showMessageDialog(this, "Sender not found!", "Error", JOptionPane.ERROR_MESSAGE);
                    conn.rollback();
                    return;
                }

                // 🔵 Check if sender has enough balance
                if (senderBalance < amount) {
                    JOptionPane.showMessageDialog(this, "Insufficient balance!", "Error", JOptionPane.ERROR_MESSAGE);
                    conn.rollback();
                    return;
                }
            }

            // 🔵 Deduct amount from sender
            String deductSender = "UPDATE tbl_users SET balance = balance - ? WHERE u_username = ?";
            try (PreparedStatement pstDeduct = conn.prepareStatement(deductSender)) {
                pstDeduct.setDouble(1, amount);
                pstDeduct.setString(2, senderUsername);
                pstDeduct.executeUpdate();
            }

            // 🔵 Add amount to receiver
            String addReceiver = "UPDATE tbl_users SET balance = balance + ? WHERE u_username = ?";
            try (PreparedStatement pstAdd = conn.prepareStatement(addReceiver)) {
                pstAdd.setDouble(1, amount);
                pstAdd.setString(2, receiverUsername);
                int receiverUpdateResult = pstAdd.executeUpdate();

                if (receiverUpdateResult == 0) {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this, "Receiver not found!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // 🔵 Insert send money transaction record
            String sql = "INSERT INTO tbl_sendmoney (sender_id, sender_username, receiver_username, amount, description, status) VALUES (?, ?, ?, ?, ?, ?)";
            try (PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setInt(1, senderId);
                pst.setString(2, senderUsername);
                pst.setString(3, receiverUsername);
                pst.setDouble(4, amount);
                pst.setString(5, "Money Sent");
                pst.setString(6, "COMPLETED");

                int result = pst.executeUpdate();

                if (result > 0) {
                    conn.commit(); // Commit transaction

                    JOptionPane.showMessageDialog(this, "Money sent successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    // Log the event
                    logEvent(senderId, senderUsername, "User Sent Money to " + receiverUsername);

                    // Clear input fields
                    Senderusername.setText("");
                    Receivername.setText("");
                    loanamount.setText("");
                } else {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this, "Failed to send money.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Transaction failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid amount.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendMoneyDashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendMoneyDashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendMoneyDashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendMoneyDashoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendMoneyDashoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Receivername;
    private javax.swing.JTextField Senderusername;
    private javax.swing.JLabel acc_fname;
    private javax.swing.JLabel acc_id;
    public javax.swing.JButton cancel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField loanamount;
    // End of variables declaration//GEN-END:variables
}
